ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE bookings ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE bookings RENAME COLUMN booking_date TO start_time;

ALTER TABLE bookings ADD COLUMN end_time TIMESTAMP;
